version: '3.7'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server-container
    environment:
      SA_PASSWORD: password123
      ACCEPT_EULA: Y
    ports:
      - 1433:1433
    volumes:
      - sql-data:/var/opt/mssql
    networks:
      - sql-net

volumes:
  sql-data:

networks:
  sql-net: